name: Print Release Version

on:
  push:
    branches: [ "versioning" ]
#  release:
#    types: [created]
permissions:
  contents: write
  pull-requests: write

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history and all tags
          persist-credentials: true  # uses GITHUB_TOKEN by default
      - name: Set release version
        run: |
          echo "${{ github.event.release.tag_name }}" > /home/runner/work/djangoDep/djangoDep/version.txt
          echo "Written version: $(cat version.txt)"
      - name: Commit and push version.txt
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 --always)
          echo -n > version.txt                      # Empty the file
          echo "$LATEST_TAG" >> version.txt         # Write the latest tag
      - name: Commit version.txt to branch
        run: |
          git checkout -b update-version-txt-${{ github.run_number }}
          git add version.txt
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "chore: update version.txt to $LATEST_TAG"
          git push origin HEAD
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore: update version.txt to ${{ env.LATEST_TAG }}"
          commit-message: "chore: update version.txt to ${{ env.LATEST_TAG }}"
          base: versioning  # Change to your target branch
          branch: update-version-txt-${{ github.run_number }}
          body: |
            This PR was created automatically to update the application version to `${{ env.LATEST_TAG }}`.
  print_version:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true
    steps:
        - name: Print Release Version
          run: |
            echo "Release version is ${{ github.event.release.tag_name }}"
#            echo "${{ github.event.release.tag_name }}" > /home/runner/work/djangoDep/djangoDep/version.txt
#            echo "Current directory is: $(pwd)"
#            echo "Absolute path to version.txt is: $(realpath version.txt)"
#            env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        - name: Print Release Name
#            run: echo "Release name is ${{ github.event.release.name }}"
#            env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
