name: Print Release Version

on:
  release:
    types: [created]

jobs:
  print_version:
    runs-on: ubuntu-latest
    steps:
        - name: Print Release Version
          run: |
            echo "Release version is ${{ github.event.release.tag_name }}"
            echo "${{ github.event.release.tag_name }}" > version.txt
#            env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        - name: Print Release Name
#            run: echo "Release name is ${{ github.event.release.name }}"
#            env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
