name: Print Release Version

on:
  push:
    branches: [ "versioning" ]
#  release:
#    types: [created]
permissions:
  contents: write

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true  # uses GITHUB_TOKEN by default
      - name: Set release version
        run: |
          echo "${{ github.event.release.tag_name }}" > /home/runner/work/djangoDep/djangoDep/version.txt
          echo "Written version: $(cat version.txt)"
      - name: Commit and push version.txt
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 --always)
          echo "Latest release tag: $LATEST_TAG"
          git add version.txt
          git commit -m "chore: update version.txt to $LATEST_TAG || echo "No changes to commit"
          git push
  print_version:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true
    steps:
        - name: Print Release Version
          run: |
            echo "Release version is ${{ github.event.release.tag_name }}"
            echo "${{ github.event.release.tag_name }}" > /home/runner/work/djangoDep/djangoDep/version.txt
            echo "Current directory is: $(pwd)"
            echo "Absolute path to version.txt is: $(realpath version.txt)"
#            env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        - name: Print Release Name
#            run: echo "Release name is ${{ github.event.release.name }}"
#            env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
